/**
 * Author:  Larissa
 * Created: set 01, 2019
 */
CREATE DATABASE agenda;
CREATE TABLE contatos(
ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL;
TELEFONE VARCHAR(12));
